[build]
  base = "frontend/"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.railway.app"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-staging-backend.railway.app"